import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// const inter = Inter({ subsets: ["latin"] });

const sfCompact = localFont({
  src: "./fonts/SF-Pro-Text-Regular.otf",
  variable: "--font-sf-text",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ramadhan Countdown",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sfCompact.variable}>
        <ThemeProvider attribute={"class"} defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
